[package]
name = "mv-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
keyring = "3.6"
zeroize = { workspace = true }
tracing = { workspace = true }
