-- MindVault Agentic Intelligence schema
-- Intents, Insights, and Chronicle for the Watcher Agent

-- Captured intents detected from knowledge nodes
CREATE TABLE IF NOT EXISTS captured_intents (
    id TEXT PRIMARY KEY NOT NULL,
    node_id TEXT NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    intent_type TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 0.5,
    parameters TEXT, -- JSON
    status TEXT NOT NULL DEFAULT 'suggested',
    created_at TEXT NOT NULL,
    updated_at TEXT
);

-- Proactive insights generated by pattern detection
CREATE TABLE IF NOT EXISTS proactive_insights (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    insight_type TEXT NOT NULL,
    related_node_ids TEXT, -- JSON array
    importance REAL NOT NULL DEFAULT 0.5,
    created_at TEXT NOT NULL,
    dismissed_at TEXT
);

-- Chronicle entries for transparency logging
CREATE TABLE IF NOT EXISTS chronicle_entries (
    id TEXT PRIMARY KEY NOT NULL,
    node_id TEXT REFERENCES knowledge_nodes(id) ON DELETE SET NULL,
    step_name TEXT NOT NULL,
    logic TEXT NOT NULL,
    input_snapshot TEXT,
    output_snapshot TEXT,
    timestamp TEXT NOT NULL
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_intents_status ON captured_intents(status);
CREATE INDEX IF NOT EXISTS idx_intents_node ON captured_intents(node_id);
CREATE INDEX IF NOT EXISTS idx_intents_type ON captured_intents(intent_type);
CREATE INDEX IF NOT EXISTS idx_intents_created ON captured_intents(created_at);

CREATE INDEX IF NOT EXISTS idx_insights_type ON proactive_insights(insight_type);
CREATE INDEX IF NOT EXISTS idx_insights_created ON proactive_insights(created_at);
CREATE INDEX IF NOT EXISTS idx_insights_dismissed ON proactive_insights(dismissed_at);

CREATE INDEX IF NOT EXISTS idx_chronicle_node ON chronicle_entries(node_id);
CREATE INDEX IF NOT EXISTS idx_chronicle_timestamp ON chronicle_entries(timestamp);
CREATE INDEX IF NOT EXISTS idx_chronicle_step ON chronicle_entries(step_name);

-- Update schema version
INSERT OR IGNORE INTO schema_version (version, applied_at) VALUES (3, datetime('now'));
